pipeline {
	agent any
    
	parameters {
		choice(name: 'workspace', choices:['test', 'uat', 'prod'], description: 'Workspace/environment file to use for deployment')
		booleanParam(name: 'destroy', defaultValue: false, description: 'Destroy the cluster?')

	}
    
    environment {
		BITBUCKET_REPO = 'git@bitbucket.org:jimmy233/backend.git'
		WORKSPACE_PATH = '/var/jenkins_home/workspace/eks'
		AWS_ACCESS_KEY_ID     = credentials('AWS_Access_Key')
		AWS_SECRET_ACCESS_KEY = credentials('AWS_Secret_Access_Key')
	}
    
	options {
		// Keep maximum 10 archievd artifacts
		buildDiscarder(logRotator(numToKeepStr:'10', artifactNumToKeepStr:'10'))
		// No simultaneous builds
		disableConcurrentBuilds()
		durabilityHint('MAX_SURVIVABILITY') // PERFORMANCE_OPTIMIZED or SURVIVABLE_NONATOMIC
	}

	stages {
		stage('Install packages') {
			steps {
				echo "Installing packages ..."
				sh 'curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp'
                sh 'sudo -n mv /tmp/eksctl /usr/local/bin'
                sh 'eksctl version'
			}
		}
    }
		
}