version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging to Amazon ECR
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=765327795183.dkr.ecr.us-east-1.amazonaws.com/bypassq
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building the Docker image
      - docker build --build-arg DB_URL=${DB_URL} --build-arg PROD_DB_URL=${PROD_DB_URL} --build-arg JWT_SECRET=${JWT_SECRET} --build-arg AWS_REGION=${AWS_REGION} --build-arg AWS_ACCESS_KEY=${AWS_ACCESS_KEY} --build-arg AWS_SECRET_KEY=${AWS_SECRET_KEY} --build-arg AWS_S3_BUCKET=${AWS_S3_BUCKET} -t $REPOSITORY_URI:$COMMIT_HASH .
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker image
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - echo Writing image definition files
      - printf '[{"name":"bypassq-task","imageUri":"%s"}]' $REPOSITORY_URI:$COMMIT_HASH > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: 
    - imagedefinitions.json
